import { Roboto } from 'next/font/google';
import '../globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <section>{children}</section>;
}
