import { Metadata } from 'next';
import Table from '@/components/Table';
import { getMenu } from '@/services/menuServices';
import { getCategories } from '@/services/categoriesServices';

export const metadata: Metadata = {
    title: 'Menu',
    description: 'Generated by create next app',
};

async function MenuPage() {
    const menuResponse = await getMenu();

    return (
        <div>
            <div className="mt-8 pb-[20px]">
                {menuResponse.error ? (
                    <div>
                        <div className="mt-8">
                            <h1>Error From Fetching Data</h1>
                        </div>
                    </div>
                ) : (
                    <Table data={menuResponse} menu></Table>
                )}
            </div>
        </div>
    );
}

export default MenuPage;
