import React from 'react';
import Header from '@/components/Header';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Waiter Home',
    description: 'Generated by create next app',
};

function WaiterHome(): React.ReactNode {
    return (
        <div>
            <div className="lg:hidden">
                <Header />
            </div>
            Waiter Home
        </div>
    );
}

export default WaiterHome;
