import { Metadata } from 'next';
import { getReservations } from '@/services/reservationServices';
import ReservationItem from '@/components/ReservationItem';
import { HiMiniMagnifyingGlass } from 'react-icons/hi2';
import { getTableList } from '@/services/tablesServices';
import TableItem from '@/components/TableItem';
import { MdTableBar } from 'react-icons/md';
import DialogTriggerCustomize from '@/components/Dialog/DialogTriggerCustomize';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import TableForm from '@/components/Form/TableForm';

export const metadata: Metadata = {
    title: 'Tables',
    description: 'Generated by create next app',
};
async function TableListPage() {
    const reservavationResponse = await getReservations();
    const tableResponse = await getTableList();

    return (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mt-4 px-4 md:p-0">
            <div className="md:col-span-1 bg-white md:h-[calc(100vh_-90px)] max:h-[calc(100vh_-90px)] md:sticky top-[70px] rounded-xl p-4">
                <div className="flex w-full">
                    <input
                        type="text"
                        placeholder="search for resevation..."
                        className="outline-none border border-black p-1 rounded-sm w-full italic flex-1"
                    />
                    <button className="min-w-[30px] hover:opacity-70 bg-secondary-cyan text-white font-semibold active:bg-primary-cyan aspect-square flex justify-center items-center border border-white rounded-sm ml-2">
                        <HiMiniMagnifyingGlass />
                    </button>
                </div>
                <div className="mt-2">
                    {reservavationResponse.error ? (
                        <p>Fetching Reservation Failed</p>
                    ) : (
                        reservavationResponse.map((ele: any, idx: number) => <ReservationItem key={idx} data={ele} />)
                    )}
                </div>
            </div>
            <div className="md:col-span-3 bg-white p-4 border rounded-xl">
                <h2 className="font-bold text-2xl flex items-center select-none mb-2">
                    <MdTableBar className="mr-2" />
                    Table List:
                </h2>
                <Dialog>
                    <DialogTriggerCustomize title="Create New Table" createType />
                    <DialogContent>
                        <DialogHeader>
                            <DialogTitle>Notice</DialogTitle>
                            <DialogDescription>Create new table in this form.</DialogDescription>
                        </DialogHeader>
                        <TableForm formType="create" data={{}} />
                    </DialogContent>
                </Dialog>
                <div className="grid grid-cols-3 gap-4 mt-4">
                    {tableResponse.error ? (
                        <p>Fetching Tables Failed</p>
                    ) : (
                        tableResponse.map((ele: any, idx: number) => (
                            <TableItem staticTable tableData={ele} key={idx} />
                        ))
                    )}
                </div>
            </div>
        </div>
    );
}

export default TableListPage;
