import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Tables',
    description: 'Generated by create next app',
};

import Header from '@/components/Header';
import TableItem from '@/components/TableItem';
import { getTableList } from '@/services/tablesServices';
import FilterBtn from '@/components/filterBtn';
import Stepper from '@/components/Stepper';

async function WaiterTable() {
    const tableList = await getTableList();

    return (
        <>
            <Header />
            <div className="px-6">
                <Stepper />
            </div>
            <div className="px-4 mt-4">
                <FilterBtn />
                <div className="mt-4 grid gap-6 pb-[80px] grid-cols-2 md:grid-cols-3">
                    {tableList.error ? (
                        <p>Fetching Tables Failed</p>
                    ) : (
                        tableList.map(
                            (
                                ele: {
                                    id: string;
                                    seating_capacity: number;
                                    status: string;
                                    createdAt: string;
                                    updatedAt: string;
                                },
                                idx: number,
                            ) => <TableItem tableData={ele} key={idx} />,
                        )
                    )}
                </div>
            </div>
        </>
    );
}

export default WaiterTable;
