import MobileNav from '@/components/MobileNav';
import type { Metadata } from 'next';
import '../../globals.css';
import SidebarProvider from '@/provider/SidebarProvider';
import Sidebar from '@/components/Sidebar';
import LayoutContainer from '@/components/LayoutContainer';
import chefRoutes from '@/routes/chefRoutes';

export const metadata: Metadata = {
    title: 'Waiter Home',
    description: 'Generated by create next app',
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            <SidebarProvider>
                <Sidebar routes={chefRoutes} />
                <LayoutContainer>
                    <div className="">{children}</div>
                    <MobileNav type="chef" />
                </LayoutContainer>
            </SidebarProvider>
        </section>
    );
}
