// 'use client';

import { useEffect, useState } from 'react';

// import { Metadata } from 'next';

// export const metadata: Metadata = {
//     title: 'Analyst',
//     description: 'Generated by create next app',
// };

function AnalystPage() {
    // const [data, setData] = useState([]);
    // useEffect(() => {
    //     const fetchData = async () => {
    //         // const res = await fetch('https://res-1-9jzz.onrender.com', {
    //         //     method: 'GET',
    //         //     cache: 'no-cache',
    //         // }).then((response) => {
    //         //     if (!response.ok) {
    //         //         throw new Error(`HTTP error! status: ${response.status}`);
    //         //     } else {
    //         //         return response.text();
    //         //     }
    //         // });
    //         // console.log(res);
    //         // const result = JSON.parse(res).data;
    //         // setData(result);
    //     };
    //     fetchData();
    // });
    // return <div>Analyst {process.env.BASE_URL}</div>;
}

export default AnalystPage;
