import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Staffs',
    description: 'Generated by create next app',
};

function StaffPage(): React.ReactNode {
    return <div>Staff</div>;
}

export default StaffPage;
