import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
};

function DashboardPage(): React.ReactNode {
    return <div className="text-cyan-400">Dashboard</div>;
}

export default DashboardPage;
